### ISSUE TITLE
Warning Error

### ISSUE THREAD

**Issue by webshellz** [dotcppfile/DAws#8]
Warning: realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): ...on line 1790

```
    <td>".floor((disk_total_space(realpath("/")))/(1073741824))." GB</td>
```

Is this something that should be fixed or is it okay?

**Comment by webshellz** [comment]
Can you make one that doesn't output error logs? I think its very sketchy.

**Comment by dotcppfile** [comment]
The reason this warning is popping up is because of the value of open_basedir, in your case.
We can try and change the value in many ways but I don't think it's worth it at all for now since this line of code gets us the size of the server and shows it to us, nothing else, that value isn't used by DAws either so it won't affect it at all.
I suggest you just replace the whole line with `<td></td>` if the warning is bothering you.

We'll release a fix for this in our free time. Thanks a lot for reporting this mate.

**Comment by webshellz** [comment]
Your welcome, it also didn't let me upload a file eaither, it was just
giving me an error message. I didn't save it but I could recreate the error
if you think its something with the shell or the server.

**Comment by dotcppfile** [comment]
I believe the error was about not being able to modify header information since it was just sent, and that is the case because the warning was popping up, the upload will work just fine if you apply the temporary solution that I suggested in my last post.
